# Generated by Django 4.2.2 on 2023-06-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0002_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
