# Generated by Django 4.2.2 on 2023-06-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0003_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
