# Generated by Django 4.2.2 on 2023-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0004_events_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
