# Generated by Django 4.2.2 on 2023-06-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0006_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
    ]
