# Generated by Django 4.2.2 on 2023-06-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0007_remove_client_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='service',
        ),
    ]
