# Generated by Django 4.2.2 on 2023-06-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0008_remove_supplier_contact_remove_supplier_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
