# Generated by Django 4.2.2 on 2023-06-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0010_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('teambuilding', 'TEAMBUILDING'), ('traditional wedding', 'TRADITIONAL WEDDING'), ('graduation party', 'GRADUATION  PARTY'), ('urban wedding', 'URBAN WEDDING'), ('christmas party', 'CHRISTMAS PARTY'), ('book launching', 'BOOK LAUNCHING'), ('festival', 'FESTIVAL'), ('educational', 'EDUCATIONAL'), ('funday', 'FUNDAY')], default='event', max_length=100),
        ),
    ]
