# Generated by Django 4.2.2 on 2023-06-24 10:22

from django.db import migrations, models
import xp_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0011_events_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(choices=[('gold', 'Gold (Recommended for large events)'), ('silver', 'Silver (Recommended for medium events)'), ('bronze', 'Bronze (Recommended for small events)')], max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('price_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('speakers', models.PositiveIntegerField()),
                ('generator', models.PositiveIntegerField()),
                ('amplifier', models.PositiveIntegerField()),
                ('mics', models.PositiveIntegerField()),
                ('has_technician', models.BooleanField(default=True)),
                ('has_dj_mc', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(validators=[xp_app.models.validate_future_date]),
        ),
    ]
