# Generated by Django 4.2.2 on 2023-06-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0012_soundpackage_alter_events_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundpackage',
            old_name='package_name',
            new_name='sound_package',
        ),
        migrations.AddField(
            model_name='supplier',
            name='package_name',
            field=models.CharField(default='awesome package', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='service',
            field=models.CharField(choices=[('decor', 'Decor'), ('videography', 'Videographer'), ('catering', 'Catering')], default='ser', max_length=200),
        ),
        migrations.CreateModel(
            name='VideoPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(limit_choices_to={'service': 'videography'}, on_delete=django.db.models.deletion.CASCADE, to='xp_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DecorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(limit_choices_to={'service': 'decor'}, on_delete=django.db.models.deletion.CASCADE, to='xp_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CateringPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(limit_choices_to={'service': 'catering'}, on_delete=django.db.models.deletion.CASCADE, to='xp_app.supplier')),
            ],
        ),
    ]
