# Generated by Django 4.2.2 on 2023-06-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0013_rename_package_name_soundpackage_sound_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='catering_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='xp_app.cateringpackage'),
        ),
        migrations.AddField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='xp_app.decorpackage'),
        ),
        migrations.AddField(
            model_name='events',
            name='sound_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='xp_app.soundpackage'),
        ),
    ]
