# Generated by Django 4.2.2 on 2023-06-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0015_alter_events_catering_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='catering_package',
        ),
        migrations.RemoveField(
            model_name='events',
            name='decor_package',
        ),
        migrations.RemoveField(
            model_name='events',
            name='sound_package',
        ),
    ]
