# Generated by Django 4.2.2 on 2023-06-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0017_events_catering_package_events_decor_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='catering_package',
        ),
        migrations.AlterField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='xp_app.decorpackage'),
        ),
        migrations.AlterField(
            model_name='events',
            name='sound_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='xp_app.soundpackage'),
        ),
    ]
