# Generated by Django 4.2.2 on 2023-06-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0020_remove_events_catering_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='catering_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xp_app.cateringpackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xp_app.decorpackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='sound_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xp_app.soundpackage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='package_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='service',
            field=models.CharField(choices=[('decor', 'Decor'), ('videography', 'Videographer'), ('catering', 'Catering')], max_length=200),
        ),
    ]
