# Generated by Django 4.2.2 on 2023-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0021_events_catering_package_events_decor_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
