# Generated by Django 4.2.2 on 2023-06-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0022_alter_supplier_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='catering_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.cateringpackage'),
        ),
        migrations.AlterField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.decorpackage'),
        ),
        migrations.AlterField(
            model_name='events',
            name='sound_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.soundpackage'),
        ),
    ]
