# Generated by Django 4.2.2 on 2023-06-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0023_alter_events_catering_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.cateringpackage')),
                ('decor_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.decorpackage')),
                ('sound_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.soundpackage')),
                ('videography_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.videopackage')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='videography_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videography_events', to='xp_app.extrapackages'),
        ),
        migrations.AlterField(
            model_name='events',
            name='catering_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catering_events', to='xp_app.extrapackages'),
        ),
        migrations.AlterField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decor_events', to='xp_app.extrapackages'),
        ),
        migrations.AlterField(
            model_name='events',
            name='sound_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound_events', to='xp_app.extrapackages'),
        ),
    ]
