# Generated by Django 4.2.2 on 2023-06-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0024_extrapackages_events_videography_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='catering_package',
        ),
        migrations.RemoveField(
            model_name='events',
            name='decor_package',
        ),
        migrations.RemoveField(
            model_name='events',
            name='sound_package',
        ),
        migrations.RemoveField(
            model_name='events',
            name='videography_package',
        ),
        migrations.AddField(
            model_name='events',
            name='extra_package',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.extrapackages'),
        ),
    ]
