# Generated by Django 4.2.2 on 2023-06-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0025_remove_events_catering_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='extra_package',
        ),
        migrations.AddField(
            model_name='events',
            name='catering_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catering_events', to='xp_app.extrapackages'),
        ),
        migrations.AddField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decor_events', to='xp_app.extrapackages'),
        ),
        migrations.AddField(
            model_name='events',
            name='sound_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound_events', to='xp_app.extrapackages'),
        ),
        migrations.AddField(
            model_name='events',
            name='videography_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videography_events', to='xp_app.extrapackages'),
        ),
    ]
