# Generated by Django 4.2.2 on 2023-06-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0026_remove_events_extra_package_events_catering_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xp_app.supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='decorpackage',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='extrapackages',
            name='catering_package',
        ),
        migrations.RemoveField(
            model_name='extrapackages',
            name='decor_package',
        ),
        migrations.RemoveField(
            model_name='extrapackages',
            name='sound_package',
        ),
        migrations.RemoveField(
            model_name='extrapackages',
            name='videography_package',
        ),
        migrations.RemoveField(
            model_name='videopackage',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='CateringPackage',
        ),
        migrations.DeleteModel(
            name='DecorPackage',
        ),
        migrations.DeleteModel(
            name='SoundPackage',
        ),
        migrations.DeleteModel(
            name='VideoPackage',
        ),
        migrations.AlterField(
            model_name='events',
            name='catering_package',
            field=models.ForeignKey(limit_choices_to={'supplier__service': 'catering'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_catering', to='xp_app.package'),
        ),
        migrations.AlterField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(limit_choices_to={'supplier__service': 'decor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_decor', to='xp_app.package'),
        ),
        migrations.AlterField(
            model_name='events',
            name='sound_package',
            field=models.ForeignKey(limit_choices_to={'supplier__service': 'sound'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_sound', to='xp_app.package'),
        ),
        migrations.AlterField(
            model_name='events',
            name='videography_package',
            field=models.ForeignKey(limit_choices_to={'supplier__service': 'videography'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_videography', to='xp_app.package'),
        ),
        migrations.DeleteModel(
            name='ExtraPackages',
        ),
    ]
