# Generated by Django 4.2.2 on 2023-06-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0027_package_remove_decorpackage_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='sound_package',
        ),
    ]
