# Generated by Django 4.2.2 on 2023-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0028_remove_events_sound_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attendees_expected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
