# Generated by Django 4.2.2 on 2023-06-26 15:28

import datetime
from django.db import migrations, models
import xp_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0029_alter_events_attendees_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[xp_app.models.validate_future_date]),
        ),
    ]
