# Generated by Django 4.2.2 on 2023-06-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0031_alter_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='username',
        ),
    ]
