# Generated by Django 4.2.2 on 2023-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0032_remove_supplier_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='username',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
