# Generated by Django 4.2.2 on 2023-06-27 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0034_alter_supplier_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
