# Generated by Django 4.2.2 on 2023-06-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0035_alter_events_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.OneToOneField(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='xp_app.venue'),
        ),
    ]
