# Generated by Django 4.2.2 on 2023-06-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0036_venue_alter_events_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='xp_app.venue'),
        ),
    ]
