# Generated by Django 4.2.2 on 2023-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0037_alter_events_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(default='venu', max_length=50),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
