# Generated by Django 4.2.2 on 2023-06-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0038_alter_events_venue_delete_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='venue',
        ),
    ]
