# Generated by Django 4.2.2 on 2023-06-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0040_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xp_app.venue'),
        ),
    ]
