# Generated by Django 4.2.2 on 2023-06-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0041_events_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='catering_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'supplier__service': 'catering'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_catering', to='xp_app.package'),
        ),
        migrations.AlterField(
            model_name='events',
            name='decor_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'supplier__service': 'decor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_decor', to='xp_app.package'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('teambuilding', 'TEAMBUILDING'), ('traditional wedding', 'TRADITIONAL WEDDING'), ('graduation party', 'GRADUATION  PARTY'), ('urban wedding', 'URBAN WEDDING'), ('christmas party', 'CHRISTMAS PARTY'), ('book launching', 'BOOK LAUNCHING'), ('festival', 'FESTIVAL'), ('educational', 'EDUCATIONAL'), ('funday', 'FUNDAY'), ('seminar', 'SEMINAR'), ('confrence', 'CONFRENCE'), ('workshop', 'WORKSHOP')], default='event', max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='videography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'supplier__service': 'videography'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_videography', to='xp_app.package'),
        ),
    ]
