# Generated by Django 4.2.2 on 2023-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0042_alter_events_catering_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
