# Generated by Django 4.2.2 on 2023-07-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0046_conversation_message_client_conversations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='conversations',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='conversations',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
