# Generated by Django 4.2.2 on 2023-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0047_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING')], default='pending', max_length=200),
        ),
    ]
