# Generated by Django 4.2.2 on 2023-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_app', '0048_events_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
