from django.urls import path
from . import views
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name= 'index'),
    path('create_user/', views.create_user, name='create_user'),
    path('user/<int:user_id>/delete/', views.delete_user, name='user_delete'),
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('adminpage/', views.admin2, name='adminpage'),
    path('customer/', views.customer, name='customer'),
    path('message/', views.messages, name='message'),
    path('logout/', views.logout, name="logout"),
    path('update_profile', views.update_profile, name='update_profile'),
    path('admin2', views.admin2, name='admin2'),
    path('messages', views.messages, name='messages'),
    path('supplier', views.supplier, name='supplier'),
    path('view_customer', views.view_customer, name='view_customer'),
    path('view_supplier', views.view_supplier, name='view_supplier'),
    path('events', views.all_events, name='events'),
    path('payment/<int:event_id>/', views.payment_view, name='payment'),
    path('reports', views.reports_view, name='reports'),
    path('users_reports', views.admin_users_report, name='users_report'),
    path('customer_report', views.customer_report_view, name='customer_report'),
    path('receipt/<int:event_id>/', views.receipts_view, name='receipt'),
    path('feedback', views.feedback, name='feedback'),
    path('view_feedback', views.view_feedback, name='view_feedback'),
    path('customer/<int:customer_id>/', views.customer_detail, name='customer_detail'),
    path('supplier/<int:customer_id>/', views.supplier_detail, name='supplier_detail'),
    path('event/<int:event_id>/update/', views.event_update, name='event_update'),
    path('event/<int:event_id>/delete/', views.event_delete, name='event_delete'),
    path('events/<int:event_id>/approve/', EventApprovalView.as_view(), name='event-approval'),
    path('create-event/', views.create_event, name='create_event'),
    path('events', views.all_events, name='events'),
    path('venues', views.venues, name='venues'),
    path('add_venue', views.create_venue, name='add_venue'),
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'),
         name='password_reset_complete'),
]